"""
Configuration module for the backend application.
"""

from .settings import Settings, get_settings, settings
from .constants import (
    # AWS
    DYNAMODB_TABLE_ARTICLES_DEV,
    DYNAMODB_TABLE_ARTICLES_PROD,
    AWS_REGION_DEFAULT,
    AWS_REGION_S3,
    GSI_CATEGORY_DATE,
    GSI_SLUG,
    # Timeouts
    HTTP_TIMEOUT_SHORT,
    HTTP_TIMEOUT_MEDIUM,
    HTTP_TIMEOUT_LONG,
    HTTP_TIMEOUT_SCRAPER,
    # Cache
    CACHE_TTL_DEFAULT,
    CACHE_TTL_VIDEO_SCHEDULES,
    REDIS_SOCKET_TIMEOUT,
    # URLs
    FRONTEND_URL_DEFAULT,
    BIGKINDS_API_URL_DEFAULT,
    ANTHROPIC_API_URL,
    NAVER_TV_URL_DEFAULT,
    # Categories
    CATEGORIES_KOREAN,
    ALL_CATEGORIES,
    CATEGORY_ENGLISH_TO_KOREAN,
    CATEGORY_KOREAN_TO_ENGLISH,
    VALID_CATEGORIES_ENGLISH,
    # Pagination
    DEFAULT_PAGE_SIZE,
    MAX_PAGE_SIZE,
    BATCH_SIZE_DYNAMODB,
    # Item Types
    ITEM_TYPE_ARTICLE,
    ITEM_TYPE_SETTINGS,
    ITEM_TYPE_COLLECTION_LOG,
    ITEM_TYPE_ARTICLE_VERSION,
    # CORS
    CORS_HEADERS,
)

__all__ = [
    # Settings
    'Settings',
    'get_settings',
    'settings',
    # AWS
    'DYNAMODB_TABLE_ARTICLES_DEV',
    'DYNAMODB_TABLE_ARTICLES_PROD',
    'AWS_REGION_DEFAULT',
    'AWS_REGION_S3',
    'GSI_CATEGORY_DATE',
    'GSI_SLUG',
    # Timeouts
    'HTTP_TIMEOUT_SHORT',
    'HTTP_TIMEOUT_MEDIUM',
    'HTTP_TIMEOUT_LONG',
    'HTTP_TIMEOUT_SCRAPER',
    # Cache
    'CACHE_TTL_DEFAULT',
    'CACHE_TTL_VIDEO_SCHEDULES',
    'REDIS_SOCKET_TIMEOUT',
    # URLs
    'FRONTEND_URL_DEFAULT',
    'BIGKINDS_API_URL_DEFAULT',
    'ANTHROPIC_API_URL',
    'NAVER_TV_URL_DEFAULT',
    # Categories
    'CATEGORIES_KOREAN',
    'ALL_CATEGORIES',
    'CATEGORY_ENGLISH_TO_KOREAN',
    'CATEGORY_KOREAN_TO_ENGLISH',
    'VALID_CATEGORIES_ENGLISH',
    # Pagination
    'DEFAULT_PAGE_SIZE',
    'MAX_PAGE_SIZE',
    'BATCH_SIZE_DYNAMODB',
    # Item Types
    'ITEM_TYPE_ARTICLE',
    'ITEM_TYPE_SETTINGS',
    'ITEM_TYPE_COLLECTION_LOG',
    'ITEM_TYPE_ARTICLE_VERSION',
    # CORS
    'CORS_HEADERS',
]
